export type SmileyConfig = { id: string, character: string, title: string, rate: number }
export const SMILEYS: SmileyConfig[] = [
  { character: "😀", id: "grinning-face", title: "Grinning Face", rate: 0.1 },
  { character: "😃", id: "grinning-face-with-big-eyes", title: "Grinning Face With Big Eyes", rate: 0.1 },
  { character: "😄", id: "grinning-face-with-smiling-eyes", title: "Grinning Face With Smiling Eyes", rate: 0.1 },
  { character: "😁", id: "beaming-face-with-smiling-eyes", title: "Beaming Face With Smiling Eyes", rate: 0.1 },
  { character: "😆", id: "grinning-squinting-face", title: "Grinning Squinting Face", rate: 0.1 },
  { character: "😅", id: "grinning-face-with-sweat", title: "Grinning Face With Sweat", rate: 0.1 },
  { character: "🤣", id: "rolling-on-the-floor-laughing", title: "Rolling On The Floor Laughing", rate: 0.1 },
  { character: "😂", id: "face-with-tears-of-joy", title: "Face With Tears Of Joy", rate: 0.1 },
  { character: "🙂", id: "slightly-smiling-face", title: "Slightly Smiling Face", rate: 0.1 },
  { character: "🙃", id: "upside-down-face", title: "Upside Down Face", rate: 0.1 },
  { character: "😉", id: "winking-face", title: "Winking Face", rate: 0.1 },
  { character: "😊", id: "smiling-face-with-smiling-eyes", title: "Smiling Face With Smiling Eyes", rate: 0.1 },
  { character: "😇", id: "smiling-face-with-halo", title: "Smiling Face With Halo", rate: 0.1 },
  { character: "🥰", id: "smiling-face-with-hearts", title: "Smiling Face With Hearts", rate: 0.1 },
  { character: "😍", id: "smiling-face-with-heart-eyes", title: "Smiling Face With Heart Eyes", rate: 0.1 },
  { character: "🤩", id: "star-struck", title: "Star Struck", rate: 0.1 },
  { character: "😘", id: "face-blowing-a-kiss", title: "Face Blowing A Kiss", rate: 0.1 },
  { character: "😗", id: "kissing-face", title: "Kissing Face", rate: 0.1 },
  { character: "😚", id: "kissing-face-with-closed-eyes", title: "Kissing Face With Closed Eyes", rate: 0.1 },
  { character: "😙", id: "kissing-face-with-smiling-eyes", title: "Kissing Face With Smiling Eyes", rate: 0.1 },
  { character: "🥲", id: "smiling-face-with-tear", title: "Smiling Face With Tear", rate: 0.1 },
  { character: "😋", id: "face-savoring-food", title: "Face Savoring Food", rate: 0.1 },
  { character: "😛", id: "face-with-tongue", title: "Face With Tongue", rate: 0.1 },
  { character: "😜", id: "winking-face-with-tongue", title: "Winking Face With Tongue", rate: 0.1 },
  { character: "🤪", id: "zany-face", title: "Zany Face", rate: 0.1 },
  { character: "😝", id: "squinting-face-with-tongue", title: "Squinting Face With Tongue", rate: 0.1 },
  { character: "🤑", id: "money-mouth-face", title: "Money Mouth Face", rate: 0.1 },
  { character: "🤗", id: "hugging-face", title: "Hugging Face", rate: 0.1 },
  { character: "🤭", id: "face-with-hand-over-mouth", title: "Face With Hand Over Mouth", rate: 0.1 },
  { character: "🤫", id: "shushing-face", title: "Shushing Face", rate: 0.1 },
  { character: "🤔", id: "thinking-face", title: "Thinking Face", rate: 0.1 },
  { character: "🤐", id: "zipper-mouth-face", title: "Zipper Mouth Face", rate: 0.1 },
  { character: "🤨", id: "face-with-raised-eyebrow", title: "Face With Raised Eyebrow", rate: 0.1 },
  { character: "😐", id: "neutral-face", title: "Neutral Face", rate: 0.1 },
  { character: "😑", id: "expressionless-face", title: "Expressionless Face", rate: 0.1 },
  { character: "😶", id: "face-without-mouth", title: "Face Without Mouth", rate: 0.1 },
  { character: "😏", id: "smirking-face", title: "Smirking Face", rate: 0.1 },
  { character: "😒", id: "unamused-face", title: "Unamused Face", rate: 0.1 },
  { character: "🙄", id: "face-with-rolling-eyes", title: "Face With Rolling Eyes", rate: 0.1 },
  { character: "😬", id: "grimacing-face", title: "Grimacing Face", rate: 0.1 },
  { character: "🤥", id: "lying-face", title: "Lying Face", rate: 0.1 },
  { character: "😌", id: "relieved-face", title: "Relieved Face", rate: 0.1 },
  { character: "😔", id: "pensive-face", title: "Pensive Face", rate: 0.1 },
  { character: "😪", id: "sleepy-face", title: "Sleepy Face", rate: 0.1 },
  { character: "🤤", id: "drooling-face", title: "Drooling Face", rate: 0.1 },
  { character: "😴", id: "sleeping-face", title: "Sleeping Face", rate: 0.1 },
  { character: "😷", id: "face-with-medical-mask", title: "Face With Medical Mask", rate: 0.1 },
  { character: "🤒", id: "face-with-thermometer", title: "Face With Thermometer", rate: 0.1 },
  { character: "🤕", id: "face-with-head-bandage", title: "Face With Head Bandage", rate: 0.1 },
  { character: "🤢", id: "nauseated-face", title: "Nauseated Face", rate: 0.1 },
  { character: "🤮", id: "face-vomiting", title: "Face Vomiting", rate: 0.1 },
  { character: "🤧", id: "sneezing-face", title: "Sneezing Face", rate: 0.1 },
  { character: "🥵", id: "hot-face", title: "Hot Face", rate: 0.1 },
  { character: "🥶", id: "cold-face", title: "Cold Face", rate: 0.1 },
  { character: "🥴", id: "woozy-face", title: "Woozy Face", rate: 0.1 },
  { character: "😵", id: "dizzy-face", title: "Dizzy Face", rate: 0.1 },
  { character: "🤯", id: "exploding-head", title: "Exploding Head", rate: 0.1 },
  { character: "🤠", id: "cowboy-hat-face", title: "Cowboy Hat Face", rate: 0.1 },
  { character: "🥳", id: "partying-face", title: "Partying Face", rate: 0.1 },
  { character: "🥸", id: "disguised-face", title: "Disguised Face", rate: 0.1 },
  { character: "😎", id: "smiling-face-with-sunglasses", title: "Smiling Face With Sunglasses", rate: 0.1 },
  { character: "🤓", id: "nerd-face", title: "Nerd Face", rate: 0.1 },
  { character: "🧐", id: "face-with-monocle", title: "Face With Monocle", rate: 0.1 },
  { character: "😕", id: "confused-face", title: "Confused Face", rate: 0.1 },
  { character: "😟", id: "worried-face", title: "Worried Face", rate: 0.1 },
  { character: "🙁", id: "slightly-frowning-face", title: "Slightly Frowning Face", rate: 0.1 },
  { character: "😮", id: "face-with-open-mouth", title: "Face With Open Mouth", rate: 0.1 },
  { character: "😯", id: "hushed-face", title: "Hushed Face", rate: 0.1 },
  { character: "😲", id: "astonished-face", title: "Astonished Face", rate: 0.1 },
  { character: "😳", id: "flushed-face", title: "Flushed Face", rate: 0.1 },
  { character: "🥺", id: "pleading-face", title: "Pleading Face", rate: 0.1 },
  { character: "😦", id: "frowning-face-with-open-mouth", title: "Frowning Face With Open Mouth", rate: 0.1 },
  { character: "😧", id: "anguished-face", title: "Anguished Face", rate: 0.1 },
  { character: "😨", id: "fearful-face", title: "Fearful Face", rate: 0.1 },
  { character: "😰", id: "anxious-face-with-sweat", title: "Anxious Face With Sweat", rate: 0.1 },
  { character: "😥", id: "sad-but-relieved-face", title: "Sad But Relieved Face", rate: 0.1 },
  { character: "😢", id: "crying-face", title: "Crying Face", rate: 0.1 },
  { character: "😭", id: "loudly-crying-face", title: "Loudly Crying Face", rate: 0.1 },
  { character: "😱", id: "face-screaming-in-fear", title: "Face Screaming In Fear", rate: 0.1 },
  { character: "😖", id: "confounded-face", title: "Confounded Face", rate: 0.1 },
  { character: "😣", id: "persevering-face", title: "Persevering Face", rate: 0.1 },
  { character: "😞", id: "disappointed-face", title: "Disappointed Face", rate: 0.1 },
  { character: "😓", id: "downcast-face-with-sweat", title: "Downcast Face With Sweat", rate: 0.1 },
  { character: "😩", id: "weary-face", title: "Weary Face", rate: 0.1 },
  { character: "😫", id: "tired-face", title: "Tired Face", rate: 0.1 },
  { character: "🥱", id: "yawning-face", title: "Yawning Face", rate: 0.1 },
  { character: "😤", id: "face-with-steam-from-nose", title: "Face With Steam From Nose", rate: 0.1 },
  { character: "😡", id: "pouting-face", title: "Pouting Face", rate: 0.1 },
  { character: "😠", id: "angry-face", title: "Angry Face", rate: 0.1 },
  { character: "🤬", id: "face-with-symbols-on-mouth", title: "Face With Symbols On Mouth", rate: 0.1 },
  { character: "👋", id: "waving-hand", title: "Waving Hand", rate: 0.1 },
  { character: "🤚", id: "raised-back-of-hand", title: "Raised Back Of Hand", rate: 0.1 },
  { character: "🖐", id: "hand-with-fingers-splayed", title: "Hand With Fingers Splayed", rate: 0.1 },
  { character: "✋", id: "raised-hand", title: "Raised Hand", rate: 0.1 },
  { character: "🖖", id: "vulcan-salute", title: "Vulcan Salute", rate: 0.1 },
  { character: "👌", id: "ok-hand", title: "Ok Hand", rate: 0.1 },
  { character: "🤌", id: "pinched-fingers", title: "Pinched Fingers", rate: 0.1 },
  { character: "🤏", id: "pinching-hand", title: "Pinching Hand", rate: 0.1 },
  { character: "🤞", id: "crossed-fingers", title: "Crossed Fingers", rate: 0.1 },
  { character: "🤟", id: "love-you-gesture", title: "Love You Gesture", rate: 0.1 },
  { character: "🤘", id: "sign-of-the-horns", title: "Sign Of The Horns", rate: 0.1 },
  { character: "👈", id: "backhand-index-pointing-left", title: "Backhand Index Pointing Left", rate: 0.1 },
  { character: "👉", id: "backhand-index-pointing-right", title: "Backhand Index Pointing Right", rate: 0.1 },
  { character: "👆", id: "backhand-index-pointing-up", title: "Backhand Index Pointing Up", rate: 0.1 },
  { character: "👇", id: "backhand-index-pointing-down", title: "Backhand Index Pointing Down", rate: 0.1 },
  { character: "👍", id: "thumbs-up", title: "Thumbs Up", rate: 0.1 },
  { character: "👎", id: "thumbs-down", title: "Thumbs Down", rate: 0.1 },
  { character: "✊", id: "raised-fist", title: "Raised Fist", rate: 0.1 },
  { character: "👊", id: "oncoming-fist", title: "Oncoming Fist", rate: 0.1 },
  { character: "🤛", id: "left-facing-fist", title: "Left Facing Fist", rate: 0.1 },
  { character: "🤜", id: "right-facing-fist", title: "Right Facing Fist", rate: 0.1 },
  { character: "👏", id: "clapping-hands", title: "Clapping Hands", rate: 0.1 },
  { character: "🙌", id: "raising-hands", title: "Raising Hands", rate: 0.1 },
  { character: "👐", id: "open-hands", title: "Open Hands", rate: 0.1 },
  { character: "🤲", id: "palms-up-together", title: "Palms Up Together", rate: 0.1 },
  { character: "🤝", id: "handshake", title: "Handshake", rate: 0.1 },
  { character: "🙏", id: "folded-hands", title: "Folded Hands", rate: 0.1 },
  { character: "🤳", id: "selfie", title: "Selfie", rate: 0.1 },
  { character: "👶", id: "baby", title: "Baby", rate: 0.1 },
  { character: "👧", id: "girl", title: "Girl", rate: 0.1 },
  { character: "🧒", id: "child", title: "Child", rate: 0.1 },
  { character: "👦", id: "boy", title: "Boy", rate: 0.1 },
  { character: "👩", id: "woman", title: "Woman", rate: 0.1 },
  { character: "🧑", id: "person", title: "Person", rate: 0.1 },
  { character: "👨", id: "man", title: "Man", rate: 0.1 },
  { character: "👩‍🦱", id: "woman-curly-hair", title: "Woman Curly Hair", rate: 0.1 },
  { character: "👨‍🦱", id: "man-curly-hair", title: "Man Curly Hair", rate: 0.1 },
  { character: "👩‍🦰", id: "woman-red-hair", title: "Woman Red Hair", rate: 0.1 },
  { character: "👨‍🦰", id: "man-red-hair", title: "Man Red Hair", rate: 0.1 },
  { character: "👱‍♀️", id: "woman-blond-hair", title: "Woman Blond Hair", rate: 0.1 },
  { character: "👱‍♂️", id: "man-blond-hair", title: "Man Blond Hair", rate: 0.1 },
  { character: "👩‍🦳", id: "woman-white-hair", title: "Woman White Hair", rate: 0.1 },
  { character: "👨‍🦳", id: "man-white-hair", title: "Man White Hair", rate: 0.1 },
  { character: "👩‍🦲", id: "woman-bald", title: "Woman Bald", rate: 0.1 },
  { character: "👨‍🦲", id: "man-bald", title: "Man Bald", rate: 0.1 },
  { character: "🧔", id: "person-beard", title: "Person Beard", rate: 0.1 },
  { character: "👵", id: "old-woman", title: "Old Woman", rate: 0.1 },
  { character: "🧓", id: "older-person", title: "Older Person", rate: 0.1 },
  { character: "👴", id: "old-man", title: "Old Man", rate: 0.1 },
  { character: "👲", id: "person-with-skullcap", title: "Person With Skullcap", rate: 0.1 },
  { character: "👳‍♀️", id: "woman-wearing-turban", title: "Woman Wearing Turban", rate: 0.1 },
  { character: "👳‍♂️", id: "man-wearing-turban", title: "Man Wearing Turban", rate: 0.1 },
  { character: "🧕", id: "woman-with-headscarf", title: "Woman With Headscarf", rate: 0.1 },
  { character: "👮‍♀️", id: "woman-police-officer", title: "Woman Police Officer", rate: 0.1 },
  { character: "👮‍♂️", id: "man-police-officer", title: "Man Police Officer", rate: 0.1 },
  { character: "👷‍♀️", id: "woman-construction-worker", title: "Woman Construction Worker", rate: 0.1 },
  { character: "👷‍♂️", id: "man-construction-worker", title: "Man Construction Worker", rate: 0.1 },
  { character: "💂‍♀️", id: "woman-guard", title: "Woman Guard", rate: 0.1 },
  { character: "💂‍♂️", id: "man-guard", title: "Man Guard", rate: 0.1 },
  { character: "🕵️‍♀️", id: "woman-detective", title: "Woman Detective", rate: 0.1 },
  { character: "🕵️‍♂️", id: "man-detective", title: "Man Detective", rate: 0.1 },
  { character: "👩‍⚕️", id: "woman-health-worker", title: "Woman Health Worker", rate: 0.1 },
  { character: "👨‍⚕️", id: "man-health-worker", title: "Man Health Worker", rate: 0.1 },
  { character: "👩‍🌾", id: "woman-farmer", title: "Woman Farmer", rate: 0.1 },
  { character: "👨‍🌾", id: "man-farmer", title: "Man Farmer", rate: 0.1 },
  { character: "👩‍🍳", id: "woman-cook", title: "Woman Cook", rate: 0.1 },
  { character: "👨‍🍳", id: "man-cook", title: "Man Cook", rate: 0.1 },
  { character: "👩‍🎓", id: "woman-student", title: "Woman Student", rate: 0.1 },
  { character: "👨‍🎓", id: "man-student", title: "Man Student", rate: 0.1 },
  { character: "👩‍🎤", id: "woman-singer", title: "Woman Singer", rate: 0.1 },
  { character: "👨‍🎤", id: "man-singer", title: "Man Singer", rate: 0.1 },
  { character: "👩‍🏫", id: "woman-teacher", title: "Woman Teacher", rate: 0.1 },
  { character: "👨‍🏫", id: "man-teacher", title: "Man Teacher", rate: 0.1 },
  { character: "👩‍🏭", id: "woman-factory-worker", title: "Woman Factory Worker", rate: 0.1 },
  { character: "👨‍🏭", id: "man-factory-worker", title: "Man Factory Worker", rate: 0.1 },
  { character: "👩‍💻", id: "woman-technologist", title: "Woman Technologist", rate: 0.1 },
  { character: "👨‍💻", id: "man-technologist", title: "Man Technologist", rate: 0.1 },
  { character: "👩‍💼", id: "woman-office-worker", title: "Woman Office Worker", rate: 0.1 },
  { character: "👨‍💼", id: "man-office-worker", title: "Man Office Worker", rate: 0.1 },
  { character: "👩‍🔧", id: "woman-mechanic", title: "Woman Mechanic", rate: 0.1 },
  { character: "👨‍🔧", id: "man-mechanic", title: "Man Mechanic", rate: 0.1 },
  { character: "👩‍🔬", id: "woman-scientist", title: "Woman Scientist", rate: 0.1 },
  { character: "👨‍🔬", id: "man-scientist", title: "Man Scientist", rate: 0.1 },
  { character: "👩‍🎨", id: "woman-artist", title: "Woman Artist", rate: 0.1 },
  { character: "👨‍🎨", id: "man-artist", title: "Man Artist", rate: 0.1 },
]

export class Smileys {
  private _characters: string[] = []

  unlock(character: string) {
    this._characters.push(character)
  }

  getRandom(): string {
    return ''
  }
}